### ISSUE TITLE
Add status bar

### ISSUE THREAD

**Issue by yair100** [ikarago/Notepad#10]
An optional status bar (that can be turned on and off in setting) at the bottom of the app with information such as line numbers etc would be nice.

**Comment by ikarago** [comment]
This is interesting. Not promising anything, but I'll keep this one in my mind when designing new features for the app. :)

**Comment by ikarago** [comment]
Added by the amazing @yaichenbaum in commit 89b5e78. 

Once more, thank you so much for adding it! :)
