### ISSUE TITLE
Support of Windows 10 Share

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#12]
Handy to share the document directly inside the app

**Comment by ikarago** [comment]
Good one! What would you expect the app to exacly share? Like just the text, or the entire .txt file?

I look forward to your answer. :)

**Comment by MarcAnt01** [comment]
I tought about sharing the .txt file, but sharing the text content could be handy, as well

**Comment by ikarago** [comment]
Awesome, thanks. :)

I have been thinking about adding this before, but I'll take this to plan out the feature even better. ;)

**Comment by MarcAnt01** [comment]
Tried it and it is functional, thanks for adding it😁
