### ISSUE TITLE
Missing select all icon

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#15]

**Comment by MarcAnt01** [comment]
I have tried to make the required changes, but cannot find the right click menu in Notepad/NotepadRs4/NotepadRs4/Views/

**Comment by ikarago** [comment]
For anything running 1809 or newer they should get the new TextBox ContextMenu containing that option already build-in there.

I'm not planning on adding it for older versions, (I just use the stock options right now) but if you really want to build it in yourself you can do so by toying around with the ContextMenu of the main TextBox on the Views/MainPage.xaml. ;)
