### ISSUE TITLE
Add an alert when closing Notepad with a file whose changes haven't been saved yet

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#16]

**Comment by ikarago** [comment]
Currently there isn't an official way to interrupt this process, but once I found a way I'll implement it right away. ;)

**Comment by MarcAnt01** [comment]
Yep, found no open source uwp software with this type of alert

**Comment by yair100** [comment]
@ikarago of course there is a way to interrupt this process! You can use the confirmAppClose capability but since it is restricted you need to get approved before you can publish it in the store.

**Comment by ikarago** [comment]
Awesome! Going to look into this. :) Thanks for the information @ATecSolution. 😎

**Comment by ikarago** [comment]
Fully implemented in commit 3d7987b. 😊

**Comment by yair100** [comment]
Great work!
