### ISSUE TITLE
Add Spell Checker

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#18]
As the right-click context menu is provided by the system adding the spell checker isn't supposed to cause issues. An example of this implementation is Unigram chat search right-click menu (designed for Anniversary Update and above, so different from the one in Notepad).

**Comment by ikarago** [comment]
Currently not planning on adding this, unless I find a method in the future that allows me to add this in a non-intrusive way.

**Comment by MarcAnt01** [comment]
What do you mean by intrusive?

**Comment by ikarago** [comment]
The red squiggely line. For some that use Notepad as a writing application this may be wanted, but for stuff I personally use the app for it's usually not wanted. So I want to look how I can find a way to make both parties happy when I have some spare time. ;)

**Comment by MarcAnt01** [comment]
Personally I would rather have it, but at the end you are the developer and it's up to you to decide what is more suited for your needs.

**Comment by Crystal-RainSlide** [comment]
Well... If it's a common .exe program, you can minify the mechanism of plugin into file existence detection: if plugin.dll exists, enable it and display its function; else, disable it and hide everything about its existence to the users.
That's non-intrusive, is it possible to implement a similar mechanism? Then things can go better.

**Comment by MarcAnt01** [comment]
> Well... If it's a common .exe program, you can minify the mechanism of plugin into file existence detection: if plugin.dll exists, enable it and display its function; else, disable it and hide everything about its existence to the users.

That's unrelated, since there are different APIs for uwp

**Comment by ikarago** [comment]
I've added a toggle to enable the Spell Checker in Settings in the latest commit (
9b017e4). It's set to off by default, but you can enable it by toggling it on.

Happy editing! 😊
