### ISSUE TITLE
Problems in creating file via explorer integration

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#21]
Steps to reproduce:
1. Set Notepad as default app for .txt file;
2. Create a .txt file from explorer context menu;
3. Open the file and modify it;
4. Press save

This point instead of saving the current file, it will ask to save it as a new file

**Comment by ikarago** [comment]
Combining this one with Issue #6, as they both find their origin in that the regular Save function is behaving as Save As.

Also found another bug when opening such files (showing the file as edited while it just has been opened without any changed made to it).

Thank you for reporting it! :)

**Comment by ikarago** [comment]
The main problem in this issue has been fixed in commit 014d6db, the side problem has been put in a seperate issue.
