### ISSUE TITLE
More options icon is non-aligned 

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#22]
![image](https://user-images.githubusercontent.com/43090263/57949076-a99c1a80-78e3-11e9-871e-5f6c5233effa.png)

**Comment by ikarago** [comment]
This is something that the CommandBar does by default when the labels are hidden. I'm aware of this (it bugs me as well) but is something that I'm not fixing. (Requires me to rework the CommandBar, and I don't think it's worth my time to do so for something so trivial.)
