### ISSUE TITLE
File marked as edited whilst it has not been edited since opening

### ISSUE THREAD

**Issue by ikarago** [ikarago/Notepad#23]
When opening a file from File Explorer it'll mark the file as Edited in the app while they've only been opened. This has been referenced in Issue #21 by me but in the end was unrelated to that particular issue.

Reproduction steps:
1) Open a file from File Explorer
2) File will open in Notepad and show the Edited mark.

This does not happen when opening a file from within the Notepad-app itself.

**Comment by yaichenbaum** [comment]
I am going to take a look and see if I can fix this one.

**Comment by yaichenbaum** [comment]
I cannot reproduce this behavior, is it possible it is already fixed?

**Comment by MarcAnt01** [comment]
Just noticed that if I make a modification and undo it, the file is shown as edited the same
(Preferred to write that here instead of opening a new ticket)
