### ISSUE TITLE
Support for Desktop Bridge for light up icon

### ISSUE THREAD

**Issue by MarcAnt01** [ikarago/Notepad#28]
This will be handy when discard changes dialog will appear, as the dialog cannot appear when app is not in foreground (I suppose uwp limitation).
Here a sample from original Notepad
![image](https://user-images.githubusercontent.com/43090263/58022676-3e825c00-7b0e-11e9-9379-3ee4d37a97f0.png)

**Comment by prayaas-a** [comment]
Not sure what you mean. What are the exact steps to trigger that behavior in the classic Notepad?

**Comment by MarcAnt01** [comment]
Closing Notepad from the taskbar while using another app

**Comment by prayaas-a** [comment]
I can't reproduce this behavior on 1903. I have seen this behavior in some Win32 apps but considering that Microsoft has been making changes to Notepad, it's possible it was changed.
@ikarago could you try reproducing this behavior with the classic Notepad?

**Comment by MarcAnt01** [comment]
It seems this feature has been removed and in the overall it doesn't worth to implement Desktop Bridge just for this small feature
