### ISSUE TITLE
MS Store version not up to date?

### ISSUE THREAD

**Issue by prayaas-a** [ikarago/Notepad#30]
I see that the latest commit is from early July and the code contains a search feature. It's missing from the version that's currently up on the Microsoft Store. In case you haven't submitted it already, you may wanna submit this version.
For further clarity in the future, perhaps there can be a document hosted here on GitHub that tracks the status of current and future releases with estimated dates of submission/arrival/approval. :)

**Comment by MarcAnt01** [comment]
> I see that the latest commit is from early July and the code contains a search feature. It's missing from the version that's currently up on the Microsoft Store. In case you haven't submitted it already, you may wanna submit this version.
> For further clarity in the future, perhaps there can be a document hosted here on GitHub that tracks the status of current and future releases with estimated dates of submission/arrival/approval. :)

The search feature isn't working properly, atm it's not more than a ui

**Comment by ikarago** [comment]
It's correct that the Store version is a bit behind the version that can be build with the source code here. The search and replace feature is currently just UI only, like @MarcAnt01 stated, as there is no functional code behind it yet.

I'll try to roll out a small update to the Store soon with the recent changes as the last published Store version is from the 30th of May. ;)

**Comment by ikarago** [comment]
There has been an update to the Store on 3 September 2019, so that should include most new improvements for the coming time. :)
