### ISSUE TITLE
Build native ARM64 packages

### ISSUE THREAD

**Issue by ikarago** [ikarago/Notepad#41]
Currently only regular ARM packages are being build. Find out how to enable proper building of ARM64 packages of this app and a way to test them before rolling out again. This so ARM64 users are able to take full advantage of their hardware while keeping the needed resources down.

**Comment by prayaas-a** [comment]
I believe I have fixed this! :)

**Comment by ikarago** [comment]
Whoaaa, awesome! 😊 Thank you much, because I've been fighting with this for a while now, not finding a working solution.

I've merged the PR and will build some packages to test once I've some time off this week. I'll keep this issue open until it has been tested working from within an Appx package.

**Comment by prayaas-a** [comment]
> Whoaaa, awesome! 😊 Thank you much, because I've been fighting with this for a while now, not finding a working solution.
> 
> I've merged the PR and will build some packages to test once I've some time off this week. I'll keep this issue open until it has been tested working from within an Appx package.

Make sure you look at the instructions to get set up for ARM builds that are in the PR description. :)

I wish Microsoft would make this easier and install the ARM64 tools automatically with the UWP workload. I don't see why they don't.

**Comment by ikarago** [comment]
Added and tested in commits 5b4aac4 by @prayaas-a and fe0409c! 😊
