### ISSUE TITLE
Tabbing does not insert \t, instead it tabs to UI controls

### ISSUE THREAD

**Issue by reddvid** [ikarago/Notepad#42]
Using version 1.9 on Windows 1909 (Rel Prev)

**Comment by ikarago** [comment]
Good catch! Will look into this to see how to keep the user in the TextBox while still providing a mean to escape it. :)

**Comment by yaichenbaum** [comment]
Would you like me to tackle this issue?

**Comment by ikarago** [comment]
Fixed by the amazing @yaichenbaum! 😎
