### ISSUE TITLE
Add 'Always on top' feature

### ISSUE THREAD

**Issue by ikarago** [ikarago/Notepad#44]
Add an option to always display the window on top, [PIP/Compact overlay](https://blogs.msdn.microsoft.com/universal-windows-app-model/2017/02/11/compactoverlay-mode-aka-picture-in-picture/) and adapt the UI to this mode.

**Comment by yair100** [comment]
Feel free to take a look at how Quick Pad implements this, and let me know if you have any questions.

**Comment by ikarago** [comment]
Awesome, will take a look at it when I can find the time soon. :D Thanks for the offer of help in the meantime 😊

**Comment by ikarago** [comment]
Added it! :)
