### ISSUE TITLE
ANSI files won't open

### ISSUE THREAD

**Issue by siomekziomek** [ikarago/Notepad#45]
Hi,
Txt files saved in ANSI won't open. When you try, it just opens blank untitled notepad instead.

Keep up the good work :)

**Comment by ikarago** [comment]
Awesome catch! Will look into this when I have some more spare time. Do you happen to have a sample ANSI .txt-file that makes the app crash or fail to load it that you're willing to share?

That could help a lot when debugging it. 😊

Once more, thank you for this bug report. 😎

**Comment by siomekziomek** [comment]
Every ANSI file I try to open is like this. I didn't encounter any crash, every time it just opens blank notepad (yours) instead of the file. UTF files loads fine.

I personally save everything in UTF-8 anyway, but for example lots of ReadMes are not, so I can't open them without classic notepad.

Here's the example:
[Read-pl.txt](https://github.com/ikarago/Notepad/files/3884188/Read-pl.txt)

**Comment by ikarago** [comment]
Awesome, will look into it when I have some spare time. Thanks for the sample. 😎
