### ISSUE TITLE
Option for silencing action notifications in app

### ISSUE THREAD

**Issue by snickler** [ikarago/Notepad#5]
Need to be able to turn off the notification of completion/cancellation of an action in the app. 

Ex) File opened, Can't save file.

I think the "Can't Save File" should only appear if there's a legitimate issue halting the saving of a file instead of cancelling the save.

**Comment by ikarago** [comment]
Is this due to personal preferences, the notification being annoying or something else? :)

**Comment by snickler** [comment]
Preference. That banner obstructs the bottom when I open a new file, etc. Every single time. :)

Regards,
Jeremy Sinclair

________________________________

**Comment by ikarago** [comment]
Awesome, thanks. :) Will take this in account when improving the in-app notifications! 😉

**Comment by ikarago** [comment]
With the newest release (v1.7.5.0) the notifications have been changed to only show failure notifications in the bottom; others will be displayed in small in the titlebar for a short period of time.

In the future there will be more updates to this to make the failure notifications even better, but for now I'll close this issue. Feel free to reopen it if things still aren't as expected, wished for. ;)
