### ISSUE TITLE
Rich Text Support

### ISSUE THREAD

**Issue by prayaas-a** [ikarago/Notepad#52]
Rich Text Support (for .rtf files) might be a good long-term goal to have. When in rich text mode, we could enable Bold, Italic, etc.

**Comment by ikarago** [comment]
While I do think having Rich Text support would be nice, it is something I chose not to implement nor planning to implement. I believe there are many great other Notepad apps that are doing this already, such as https://github.com/UWPCommunity/Quick-Pad and my goal with this app was to build a Notepad app that is as (bare) basic and easy to use as possible, while updating its looks to more modern standards. 

Feel free to use this app as a basis for one that does fully support Rich Text Editing though. 😊
