### ISSUE TITLE
Col doesn't update properly

### ISSUE THREAD

**Issue by prayaas-a** [ikarago/Notepad#54]
In the status bar, Line updates but Col doesn't reset to 1 when a new line is inserted.

![image](https://user-images.githubusercontent.com/44937981/71433202-bb307680-26ab-11ea-898e-e97caf7a6fa4.png)

As you can see, the current selection isn't at 19.

**Comment by ikarago** [comment]
Fixed by @prayaas-a in commit 0f09272 😎

Thank you! 😊
