### ISSUE TITLE
Saving an existing file should write back instead of invoking save dialog

### ISSUE THREAD

**Issue by snickler** [ikarago/Notepad#6]
We should be able to save an existing file without a save dialog. If a save dialog is desired, a Save As function would work.

**Comment by ATecSolution** [comment]
I am actually working on the same exact thing for my app, so far I can get it to save without the save dialog by giving the app the broad file access restricted capability in the app manifest, what I am having trouble with is checking if the user gave or denied access to the app for the file permission in windows settings. I am sure there is another way to do this so let me know what you come up with.

**Comment by ikarago** [comment]
This had been fixed in commit 014d6db! 😉
