### ISSUE TITLE
Fix command bar

### ISSUE THREAD

**Issue by yair100** [ikarago/Notepad#9]
Reveal affect does not look good on the command bar since the button to show more is bigger then the other buttons.
![image](https://user-images.githubusercontent.com/39923744/52294277-e3ee3700-2946-11e9-87b6-2721a532a00c.png)

**Comment by ikarago** [comment]
This is the standard behavior for reveal on the CommandBarButton when the project targets anything from 16299 (Fall Creators Update) and upwards.

I'm putting a won't fix label on this, as this is an SDK issue and not an design/application issue.

**Comment by yair100** [comment]
Is this a known bug that will be fixed from Microsoft?

**Comment by ikarago** [comment]
Tbh, no clue on whether this was a bug (that came with the change to smaller icons) or intentional, so my best guess is trying to contact someone from Microsoft working in this on Twitter to ask them about it. ;)

**Comment by ATecSolution** [comment]
I know in the XAML controls gallery app it says there is a new compact mode coming in windows soon, I would assume you get the option still have the regular ‘not compact’ mode. I don’t have twitter so do you think you can try to reach someone who works on this?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by yair100** [comment]
In 19h1 builds the snip and sketch tool has the compact mode and looks fine
![image](https://user-images.githubusercontent.com/39923744/52375177-0b1f3400-2a2d-11e9-915f-ba849cb58908.png)
